<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Schema;

class ExportSchemaMarkdown extends Command
{
    protected $signature = 'export:schema-markdown
        {--path=docs/database-schema.md : Path relative to the application base path}';

    protected $description = 'Export database tables and columns to a Markdown file (for API/client parity notes)';

    public function handle(): int
    {
        $relative = (string) $this->option('path');
        $full = base_path($relative);
        $dir = dirname($full);
        if (! is_dir($dir)) {
            File::makeDirectory($dir, 0755, true);
        }

        $tables = Schema::getTables();
        usort($tables, fn ($a, $b) => strcmp($a['name'], $b['name']));

        $lines = [
            '# Database schema',
            '',
            'Generated by `php artisan export:schema-markdown`.',
            '',
        ];

        foreach ($tables as $table) {
            $name = $table['name'] ?? '';
            if ($name === '') {
                continue;
            }
            $lines[] = '## `'.$name.'`';
            if (! empty($table['engine'])) {
                $lines[] = '- Engine: '.$table['engine'];
            }
            $lines[] = '';
            $lines[] = '| Column | Type | Nullable | Default | Comment |';
            $lines[] = '| --- | --- | --- | --- | --- |';

            foreach (Schema::getColumns($name) as $col) {
                $lines[] = sprintf(
                    '| `%s` | %s | %s | %s | %s |',
                    $col['name'],
                    $col['type_name'] ?? ($col['type'] ?? ''),
                    ! empty($col['nullable']) ? 'yes' : 'no',
                    $this->formatDefault($col['default'] ?? null),
                    $col['comment'] ?? ''
                );
            }
            $lines[] = '';
        }

        File::put($full, implode("\n", $lines));
        $this->info('Wrote '.$full);

        return self::SUCCESS;
    }

    private function formatDefault(mixed $default): string
    {
        if ($default === null) {
            return '';
        }
        if (is_string($default)) {
            return str_replace('|', '\\|', $default);
        }

        return json_encode($default) ?: '';
    }
}
